modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "playerbot"
version = "${version}"
displayName = "玩家机器人"
authors = "xiaofan"
description = '''
玩家机器人 - 自动化宏功能模组
'''
#logoFile = ""

[[dependencies.playerbot]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerbot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerbot]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.playerbot]]
modId = "baritoe"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"